# Generated by Django 3.2.6 on 2021-08-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='x_pos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='region',
            name='z_pos',
            field=models.IntegerField(default=0),
        ),
    ]
